version: "3.8"

services:
  neo4j:
    image: neo4j:5
    container_name: neo4j
    environment:
      # NEO4J_AUTH: "neo4j/myneo4jpassword"
      NEO4J_AUTH: "${NEO4J_USER}/${NEO4J_PASSWORD}"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  fastapi_1:
    build: ./fastapi_app1
    container_name: fastapi_app1_container
    image: fastapi_app1:latest
    ports:
      - "8001:8001"
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: "${NEO4J_USER}"
      NEO4J_PASSWORD: "${NEO4J_PASSWORD}"
    depends_on:
      - neo4j

  fastapi_2:
    build: ./fastapi_app2
    container_name: fastapi_app2_container
    image: fastapi_app2:latest
    ports:
      - "8002:8002"
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: "${NEO4J_USER}"
      NEO4J_PASSWORD: "${NEO4J_PASSWORD}"
    depends_on:
      - neo4j

volumes:
  neo4j_data:
