# ============================
# FastAPI App 1 - Deployment
# ============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-app1
  template:
    metadata:
      labels:
        app: fastapi-app1
    spec:
      containers:
      - name: fastapi-app1
        image: fastapi_app1:latest       # <-- YOUR IMAGE NAME
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        env:
        - name: NEO4J_URI
          valueFrom:
            configMapKeyRef:
              name: neo4j-config
              key: NEO4J_URI
        # - name: NEO4J_AUTH
        #   valueFrom:
        #     secretKeyRef:
        #       name: neo4j-secret
        #       key: neo4j-auth

        - name: NEO4J_USER
          valueFrom:
            secretKeyRef:
              name: neo4j-secret
              key: NEO4J_USER

        - name: NEO4J_PASSWORD
          valueFrom:
            secretKeyRef:
              name: neo4j-secret
              key: NEO4J_PASSWORD

---
# ============================
# FastAPI App 1 - Service
# ============================
apiVersion: v1
kind: Service
metadata:
  name: fastapi-app1
spec:
  type: NodePort
  selector:
    app: fastapi-app1
  ports:
  - port: 8001
    targetPort: 8001
    nodePort: 30081
